### ISSUE TITLE
auto add __dirname + '/'

### ISSUE THREAD

**Issue by 1wheel** [mhkeller/indian-ocean#57]
probably a bad idea... but I hate typing it over and over and over and over

**Comment by mhkeller** [comment]
Adding in some more detail from our chat elsewhere about this. 

The desired behavior is avoiding having to write `io.readDataSync(__dirname + '/files/file.csv')` in favor of `io.readDataSync('files/file.csv')`. Generally a safer approach is to run your scripts via [npm scripts](https://docs.npmjs.com/misc/scripts) and to use full paths so that you never run into the situation where your script changes output depending on where you run it from. 

I could see this shorthand being useful though maybe through an option like `io.readDataSync('files/file.csv, {localPath: true})`. It makes it more explicit about your intentions? What do you think @1wheel? Or would that be just as annoying (and more to type) than putting in `__dirname`?

**Comment by 1wheel** [comment]
After more thought, I don't think that is actually possible. `io` doesn't have any way of knowing what the calling script's `__dirname` should be.  

Sorry to rant in your issues! I've been trying to write my scrapers with less copy/pasting https://github.com/1wheel/scrape-stl
